/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. teste 
 */
package view;

import IO.Manipulador;
import controller.CadastroEleitor;
import controller.CadastroCandidato;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import model.Candidato;
import model.Eleitor;

/**
 *
 * @author Cleiton
 */
public class telaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    int i = 0;
    String path;
    List<Candidato> listaCandidatosInicial = new ArrayList<>();
    List<Eleitor> listaEleitoresInicial = new ArrayList<>();

    public telaInicial(List listaEleitores, List listaCandidatos) {
        initComponents();
        apagarTelas();
        this.listaEleitoresInicial = listaEleitores; // faz copia da lista eleitores
        this.listaCandidatosInicial = listaCandidatos;// faz copia da lista candidatos
        telaPrincipal.setVisible(true);
    }

    private telaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btl_importa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_exportaUrna = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_cadastraEleitor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bt_exportaTse = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bt_cadastraCandidato = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        telas = new javax.swing.JPanel();
        telaCandidato = new javax.swing.JPanel();
        jLabel_tituloCadastrarCandidato = new javax.swing.JLabel();
        jLabel_nomeCandidato = new javax.swing.JLabel();
        jLabel_matriculaCandidato = new javax.swing.JLabel();
        jLabel_idadeCandidato = new javax.swing.JLabel();
        jTextField_nomeCandidato = new javax.swing.JTextField();
        jTextField_matriculaCandidato = new javax.swing.JTextField();
        jTextField_idadeCandidato = new javax.swing.JTextField();
        bt_salvarCandidato = new javax.swing.JLabel();
        bt_visualizarListaCandidato = new javax.swing.JLabel();
        bt_anexarFotoCandidato = new javax.swing.JLabel();
        jLTeste = new javax.swing.JLabel();
        telaEleitor = new javax.swing.JPanel();
        jLabel_tituloCadastraEleitor = new javax.swing.JLabel();
        jLabel_nomeEleitor = new javax.swing.JLabel();
        jLabel_matriculaEleitor = new javax.swing.JLabel();
        jLabel_idadeEleitor = new javax.swing.JLabel();
        jTextField_nomeEleitor = new javax.swing.JTextField();
        jTextField_matriculaEleitor = new javax.swing.JTextField();
        jTextField_idadeEleitor = new javax.swing.JTextField();
        bt_salvarEleitor = new javax.swing.JLabel();
        bt_visualizarListaEleitor = new javax.swing.JLabel();
        telaExportarTSE = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        telaExportarUrna = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        telaImportar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        telaPrincipal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        menu.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));

        btl_importa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImportarDados.jpg"))); // NOI18N
        btl_importa.setText("jLabel1");
        btl_importa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btl_importaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btl_importa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btl_importa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        bt_exportaUrna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ExportarURNA.jpg"))); // NOI18N
        bt_exportaUrna.setText("jLabel4");
        bt_exportaUrna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_exportaUrnaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_exportaUrna, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_exportaUrna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));

        bt_cadastraEleitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CadEleitor.jpg"))); // NOI18N
        bt_cadastraEleitor.setText("jLabel2");
        bt_cadastraEleitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_cadastraEleitorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_cadastraEleitorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_cadastraEleitorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cadastraEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cadastraEleitor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 200));

        bt_exportaTse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ExportarTSE.jpg"))); // NOI18N
        bt_exportaTse.setText("jLabel5");
        bt_exportaTse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_exportaTseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_exportaTse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_exportaTse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 200));

        bt_cadastraCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CadCanditado.jpg"))); // NOI18N
        bt_cadastraCandidato.setText("jLabel3");
        bt_cadastraCandidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_cadastraCandidatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_cadastraCandidatoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_cadastraCandidatoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cadastraCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cadastraCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(152, 163, 199));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1285, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        telas.setBackground(new java.awt.Color(255, 255, 255));
        telas.setLayout(null);

        jLabel_tituloCadastrarCandidato.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        jLabel_tituloCadastrarCandidato.setText("Cadastrar Candidato");

        jLabel_nomeCandidato.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jLabel_nomeCandidato.setText("Nome");

        jLabel_matriculaCandidato.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jLabel_matriculaCandidato.setText("Matricula");

        jLabel_idadeCandidato.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jLabel_idadeCandidato.setText("Idade");

        jTextField_nomeCandidato.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jTextField_nomeCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomeCandidatoActionPerformed(evt);
            }
        });

        jTextField_matriculaCandidato.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N

        jTextField_idadeCandidato.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N

        bt_salvarCandidato.setText("Salvar Candidato");
        bt_salvarCandidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_salvarCandidatoMousePressed(evt);
            }
        });

        bt_visualizarListaCandidato.setText("Visualizar Lista de Candidato");
        bt_visualizarListaCandidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_visualizarListaCandidatoMousePressed(evt);
            }
        });

        bt_anexarFotoCandidato.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        bt_anexarFotoCandidato.setText("Anexar Foto");
        bt_anexarFotoCandidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_anexarFotoCandidatoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout telaCandidatoLayout = new javax.swing.GroupLayout(telaCandidato);
        telaCandidato.setLayout(telaCandidatoLayout);
        telaCandidatoLayout.setHorizontalGroup(
            telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_anexarFotoCandidato)
                    .addComponent(jLabel_nomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_visualizarListaCandidato)
                        .addGroup(telaCandidatoLayout.createSequentialGroup()
                            .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_matriculaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_idadeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_matriculaCandidato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                                .addComponent(jTextField_nomeCandidato, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_idadeCandidato)))))
                .addGap(321, 321, 321))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                .addGap(0, 596, Short.MAX_VALUE)
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                        .addComponent(jLabel_tituloCadastrarCandidato)
                        .addGap(602, 602, 602))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                        .addComponent(bt_salvarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addComponent(jLTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        telaCandidatoLayout.setVerticalGroup(
            telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tituloCadastrarCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_matriculaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_matriculaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idadeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_idadeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvarCandidato)
                    .addComponent(bt_visualizarListaCandidato))
                .addGap(2, 2, 2)
                .addComponent(bt_anexarFotoCandidato)
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        telas.add(telaCandidato);
        telaCandidato.setBounds(0, 0, 1370, 450);

        telaEleitor.setBackground(new java.awt.Color(233, 233, 233));

        jLabel_tituloCadastraEleitor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        jLabel_tituloCadastraEleitor.setText("Cadastrar Eleitor");

        jLabel_nomeEleitor.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jLabel_nomeEleitor.setText("Nome");

        jLabel_matriculaEleitor.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jLabel_matriculaEleitor.setText("Matricula");

        jLabel_idadeEleitor.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jLabel_idadeEleitor.setText("Idade");

        jTextField_nomeEleitor.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jTextField_nomeEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomeEleitorActionPerformed(evt);
            }
        });

        jTextField_matriculaEleitor.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N

        jTextField_idadeEleitor.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N

        bt_salvarEleitor.setText("Salvar Eleitor");
        bt_salvarEleitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_salvarEleitorMousePressed(evt);
            }
        });

        bt_visualizarListaEleitor.setText("Visualizar Lista de Eleitor");
        bt_visualizarListaEleitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_visualizarListaEleitorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout telaEleitorLayout = new javax.swing.GroupLayout(telaEleitor);
        telaEleitor.setLayout(telaEleitorLayout);
        telaEleitorLayout.setHorizontalGroup(
            telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEleitorLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nomeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(telaEleitorLayout.createSequentialGroup()
                            .addComponent(bt_salvarEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)
                            .addComponent(bt_visualizarListaEleitor))
                        .addGroup(telaEleitorLayout.createSequentialGroup()
                            .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_matriculaEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_idadeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_nomeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_matriculaEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_idadeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEleitorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_tituloCadastraEleitor)
                .addGap(602, 602, 602))
        );
        telaEleitorLayout.setVerticalGroup(
            telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEleitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tituloCadastraEleitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nomeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nomeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_matriculaEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_matriculaEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idadeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_idadeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(telaEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_visualizarListaEleitor)
                    .addComponent(bt_salvarEleitor))
                .addGap(136, 136, 136))
        );

        telas.add(telaEleitor);
        telaEleitor.setBounds(0, 0, 1370, 450);

        jLabel20.setText("jLabel20");

        jLabel21.setText("Exportar dados eleitor");

        jLabel22.setText("Expoartar dados da votação");

        javax.swing.GroupLayout telaExportarTSELayout = new javax.swing.GroupLayout(telaExportarTSE);
        telaExportarTSE.setLayout(telaExportarTSELayout);
        telaExportarTSELayout.setHorizontalGroup(
            telaExportarTSELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaExportarTSELayout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(613, 613, 613))
            .addGroup(telaExportarTSELayout.createSequentialGroup()
                .addGroup(telaExportarTSELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaExportarTSELayout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel20))
                    .addGroup(telaExportarTSELayout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaExportarTSELayout.setVerticalGroup(
            telaExportarTSELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaExportarTSELayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(63, 63, 63)
                .addComponent(jLabel22)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        telas.add(telaExportarTSE);
        telaExportarTSE.setBounds(0, 0, 1370, 450);

        jLabel18.setText("Exportar dados candidato");

        jLabel19.setText("Exportar dados eleitor");

        javax.swing.GroupLayout telaExportarUrnaLayout = new javax.swing.GroupLayout(telaExportarUrna);
        telaExportarUrna.setLayout(telaExportarUrnaLayout);
        telaExportarUrnaLayout.setHorizontalGroup(
            telaExportarUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaExportarUrnaLayout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(79, 79, 79)
                .addComponent(jLabel19)
                .addGap(441, 441, 441))
        );
        telaExportarUrnaLayout.setVerticalGroup(
            telaExportarUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaExportarUrnaLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(telaExportarUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(275, Short.MAX_VALUE))
        );

        telas.add(telaExportarUrna);
        telaExportarUrna.setBounds(0, 0, 1370, 450);

        jLabel8.setText("Importar Candidatos");

        jLabel16.setText("Importar Eleitores");

        jLabel17.setText("Importar Dados Vaotação");

        javax.swing.GroupLayout telaImportarLayout = new javax.swing.GroupLayout(telaImportar);
        telaImportar.setLayout(telaImportarLayout);
        telaImportarLayout.setHorizontalGroup(
            telaImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaImportarLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel8)
                .addGap(128, 128, 128)
                .addComponent(jLabel16)
                .addGap(101, 101, 101)
                .addComponent(jLabel17)
                .addContainerGap(686, Short.MAX_VALUE))
        );
        telaImportarLayout.setVerticalGroup(
            telaImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaImportarLayout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(telaImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(213, 213, 213))
        );

        telas.add(telaImportar);
        telaImportar.setBounds(0, 0, 1370, 450);

        jLabel6.setText("Cartorio Eleitoral Principal");

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaPrincipalLayout.createSequentialGroup()
                .addContainerGap(665, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(557, 557, 557))
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaPrincipalLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        telas.add(telaPrincipal);
        telaPrincipal.setBounds(0, -2, 1370, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(telas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(telas, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apagarTelas() { // tela os dados com vazio
        telaCandidato.setVisible(false);
        telaPrincipal.setVisible(false);
        telaEleitor.setVisible(false);
        telaImportar.setVisible(false);
        telaExportarTSE.setVisible(false);
        telaExportarUrna.setVisible(false);

    }

    private void bt_cadastraEleitorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastraEleitorMousePressed
        apagarTelas();
        telaEleitor.setVisible(true);
    }//GEN-LAST:event_bt_cadastraEleitorMousePressed

    private void bt_cadastraCandidatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastraCandidatoMousePressed
        apagarTelas();
        telaCandidato.setVisible(true);
    }//GEN-LAST:event_bt_cadastraCandidatoMousePressed

    private void bt_cadastraEleitorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastraEleitorMouseEntered

    }//GEN-LAST:event_bt_cadastraEleitorMouseEntered

    private void bt_cadastraEleitorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastraEleitorMouseExited

    }//GEN-LAST:event_bt_cadastraEleitorMouseExited

    private void bt_cadastraCandidatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastraCandidatoMouseEntered

    }//GEN-LAST:event_bt_cadastraCandidatoMouseEntered

    private void bt_cadastraCandidatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastraCandidatoMouseExited

    }//GEN-LAST:event_bt_cadastraCandidatoMouseExited

    private void jTextField_nomeEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomeEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomeEleitorActionPerformed

    private void jTextField_nomeCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomeCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomeCandidatoActionPerformed

    private void bt_salvarEleitorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salvarEleitorMousePressed

        CadastroEleitor.cadastrarEleitor(jTextField_nomeEleitor.getText(), Integer.parseInt(jTextField_matriculaEleitor.getText()), Integer.parseInt(jTextField_idadeEleitor.getText()), listaEleitoresInicial);
        jTextField_idadeEleitor.setText("");
        jTextField_matriculaEleitor.setText("");
        jTextField_nomeEleitor.setText("");

        jTextField_nomeEleitor.requestFocus();// cursor do mouse para nome 

    }//GEN-LAST:event_bt_salvarEleitorMousePressed

    private void btl_importaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btl_importaMousePressed
        apagarTelas();
        telaImportar.setVisible(true);
    }//GEN-LAST:event_btl_importaMousePressed

    private void bt_exportaUrnaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exportaUrnaMousePressed
        apagarTelas();
        telaExportarUrna.setVisible(true);
    }//GEN-LAST:event_bt_exportaUrnaMousePressed

    private void bt_exportaTseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exportaTseMousePressed
        apagarTelas();
        telaExportarTSE.setVisible(true);
    }//GEN-LAST:event_bt_exportaTseMousePressed

    private void bt_salvarCandidatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salvarCandidatoMousePressed
        System.out.println(path);
        CadastroCandidato.cadastrarCandidato(0,path, jTextField_nomeCandidato.getText(), Integer.parseInt(jTextField_matriculaCandidato.getText()), Integer.parseInt(jTextField_idadeCandidato.getText()), listaCandidatosInicial);
        jTextField_idadeCandidato.setText("");
        jTextField_matriculaCandidato.setText("");
        jTextField_nomeCandidato.setText("");
        jTextField_nomeCandidato.requestFocus();// cursor do mouse para nome 


    }//GEN-LAST:event_bt_salvarCandidatoMousePressed

    private void bt_visualizarListaCandidatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_visualizarListaCandidatoMousePressed
        System.out.println("Tamanho aki - " + this.listaCandidatosInicial.size());
        TabelaCandidatos tela = new TabelaCandidatos(this.listaCandidatosInicial);

        tela.setVisible(true);

    }//GEN-LAST:event_bt_visualizarListaCandidatoMousePressed

    private void bt_visualizarListaEleitorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_visualizarListaEleitorMousePressed

        tabelaEleitores tela = new tabelaEleitores(this.listaEleitoresInicial);

        tela.setVisible(true);
    }//GEN-LAST:event_bt_visualizarListaEleitorMousePressed

    private void bt_anexarFotoCandidatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_anexarFotoCandidatoMousePressed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        if (jfc.showOpenDialog(bt_anexarFotoCandidato)==JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            jLTeste.setIcon(new ImageIcon(f.toString()));
            path = f.toString();
        }
    }//GEN-LAST:event_bt_anexarFotoCandidatoMousePressed

    /**
     * @param args the command linHe arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_anexarFotoCandidato;
    private javax.swing.JLabel bt_cadastraCandidato;
    private javax.swing.JLabel bt_cadastraEleitor;
    private javax.swing.JLabel bt_exportaTse;
    private javax.swing.JLabel bt_exportaUrna;
    private javax.swing.JLabel bt_salvarCandidato;
    private javax.swing.JLabel bt_salvarEleitor;
    private javax.swing.JLabel bt_visualizarListaCandidato;
    private javax.swing.JLabel bt_visualizarListaEleitor;
    private javax.swing.JLabel btl_importa;
    private javax.swing.JLabel jLTeste;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_idadeCandidato;
    private javax.swing.JLabel jLabel_idadeEleitor;
    private javax.swing.JLabel jLabel_matriculaCandidato;
    private javax.swing.JLabel jLabel_matriculaEleitor;
    private javax.swing.JLabel jLabel_nomeCandidato;
    private javax.swing.JLabel jLabel_nomeEleitor;
    private javax.swing.JLabel jLabel_tituloCadastraEleitor;
    private javax.swing.JLabel jLabel_tituloCadastrarCandidato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField_idadeCandidato;
    private javax.swing.JTextField jTextField_idadeEleitor;
    private javax.swing.JTextField jTextField_matriculaCandidato;
    private javax.swing.JTextField jTextField_matriculaEleitor;
    private javax.swing.JTextField jTextField_nomeCandidato;
    private javax.swing.JTextField jTextField_nomeEleitor;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel telaCandidato;
    private javax.swing.JPanel telaEleitor;
    private javax.swing.JPanel telaExportarTSE;
    private javax.swing.JPanel telaExportarUrna;
    private javax.swing.JPanel telaImportar;
    private javax.swing.JPanel telaPrincipal;
    private javax.swing.JPanel telas;
    // End of variables declaration//GEN-END:variables
}
